# Generated by Django 4.2.27 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_superadmin",
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
