# Generated by Django 4.2.27 on 2026-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="uploads/myprofile_photo/default.jpg",
                upload_to="uploads/myprofile_photo/",
            ),
        ),
    ]
