# Generated by Django 4.2.27 on 2026-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image_pg",
            field=models.ImageField(
                blank=True,
                default="uploads/blog_image_on_blog/blog_default.jpg",
                upload_to="uploads/blog_image_on_blog",
            ),
        ),
    ]
