# Generated by Django 4.2.27 on 2026-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("draft", "draft"), ("published", "published")],
                default="Draft",
                max_length=50,
            ),
        ),
    ]
