# Generated by Django 4.2.27 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_alter_blog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image_pg",
            field=models.ImageField(blank=True, upload_to="uploads/blog_image_on_blog"),
        ),
    ]
