# Generated by Django 4.2.27 on 2026-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_comment_image_commentreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                default="uploads/featured_image/default.jpg",
                upload_to="uploads/featured_image",
            ),
        ),
    ]
