# Generated by Django 4.2.27 on 2026-01-28 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0004_blog_image_pg"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("draft", "draft"), ("published", "published")],
                default="draft",
                max_length=50,
            ),
        ),
    ]
