# Generated by Django 4.2.27 on 2026-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0005_category_user_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
