# Generated by Django 4.2.27 on 2026-02-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0005_blog_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="stories.blog",
            ),
        ),
    ]
